/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_silentpayapp_free: (a: number, b: number) => void;
export const recoveryWifFromSnapshot: (a: number, b: number) => void;
export const silentpayapp_currentPayment: (a: number, b: number) => void;
export const silentpayapp_exportSnapshot: (a: number, b: number) => void;
export const silentpayapp_fromSnapshot: (a: number, b: number) => void;
export const silentpayapp_new: () => number;
export const silentpayapp_paymentQrSvg: (a: number, b: number) => void;
export const silentpayapp_pollOnce: (a: number) => number;
export const silentpayapp_recoveryWif: (a: number, b: number) => void;
export const silentpayapp_reset: (a: number, b: number) => void;
export const silentpayapp_retryBroadcast: (a: number) => number;
export const silentpayapp_setRecipient: (a: number, b: number, c: number) => void;
export const start: () => void;
export const version: (a: number) => void;
export const rustsecp256k1_v0_10_0_context_create: (a: number) => number;
export const rustsecp256k1_v0_10_0_context_destroy: (a: number) => void;
export const rustsecp256k1_v0_10_0_default_error_callback_fn: (a: number, b: number) => void;
export const rustsecp256k1_v0_10_0_default_illegal_callback_fn: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_1159: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_1161: (a: number, b: number, c: number, d: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
export const __wbindgen_export5: (a: number, b: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_start: () => void;
